services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\MediaObjectBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Bridge,Resources,PhpGuildMediaObjectBundle.php}'

  PhpGuild\MediaObjectBundle\EventSubscriber\DoctrineClassMetadata\:
    resource: ../../EventSubscriber/DoctrineClassMetadata
    tags:
      - { name: doctrine.event_subscriber, priority: 256 }
