services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\MediaObjectBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Bridge,Resources,PhpGuildMediaObjectBundle.php}'

  PhpGuild\MediaObjectBundle\EventSubscriber\MediaObjectSubscriber:
    tags: [ doctrine.event_subscriber ]

  PhpGuild\MediaObjectBundle\EventSubscriber\FileMetadataSubscriber:
    tags: [ doctrine.event_subscriber ]
